Session_12/miproyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('peliculas.urls')),
]

Session_12/peliculas/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<pk>', views.DirectorView.as_view(), name='detalle_director'),
    path('pelicula/<pk>', views.PeliculaView.as_view(), name='detalle_pelicula'),
]

Session_12/peliculas/models.py
from django.db import models

# Create your models here.
class Director(models.Model):
    nombre = models.CharField(max_length=25)
    apellidos = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    biografia = models.TextField()
    imagen = models.URLField()

    def __str__(self):
        return self.nombre + " " + self.apellidos 

class Pelicula(models.Model):
    director = models.ForeignKey('Director', on_delete=models.SET_NULL, null=True)
    nombre = models.CharField(max_length=25)
    sinopsis = models.TextField(max_length=100, help_text='De que trata la pelicula')
    duracion = models.PositiveIntegerField(help_text='Cuanto dura la pelicula en minutos')
    imagen = models.URLField()
    anyo = models.PositiveIntegerField(help_text='Año de publicación de la pelicula')

    def __str__(self):
        return self.nombre

Session_12/peliculas/views.py
from django.views import generic

from .models import Director, Pelicula

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'peliculas/directores.html'
    model = Director

class DirectorView(generic.DetailView):
    template_name = 'peliculas/director.html'
    model = Director

class PeliculaView(generic.DetailView):
    template_name = 'peliculas/pelicula.html'
    model = Pelicula

Session_12/peliculas/templates/peliculas/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
        <blockquote class="blockquote text-center">
            <h1><ins>{% block header-title %}Directores{% endblock %}</ins></h1>
        </blockquote>
    </header>
    <main>{% block content %}{% endblock %}</main>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Session_12/peliculas/templates/peliculas/director.html
{% extends "peliculas/base.html" %}

{% block title %}Director - {{ director }}{% endblock %}

{% block header-title %}{{ director }}{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Año Nacimiento</th>
            <th scope="col">Biografía</th>
            <th scope="col">Películas</th>
            <th scope="col">Información Pelicula</th>
        </tr>
        <tbody>
            <tr>
                <td> {{ director.fecha_nacimiento}} </td>
                <td> {{ director.biografia | linebreaks }}</td>
                {% for pelicula in director.pelicula_set.all %}
                    <td> <span class="nombre_pelicula">{{ pelicula }}</span>
                    <td>
                        <blockquote class="blockquote text-left">
                            <a href='/pelicula/{{pelicula.id}}' target="_parent"><buttontype="button" class="btn btn-info">Ver Pelicula</button></a>
                          </blockquote>
                    </td>
                    {% cycle '' '' '' %}
                {% empty %}
                    <td>No hay peliculas aún</td>
                {% endfor %}</td>
            </tr>
            
        </tbody>
    </thead>
</table>

<blockquote class="blockquote text-center">
    <a href="http://localhost:8000/" target="_parent"><buttontype="button" class="btn btn-info">Regresar al Inicio</button></a>
  </blockquote>

{% endblock %}

Session_12/peliculas/templates/peliculas/directores.html
{% extends "peliculas/base.html" %}

{% block title %}Directores{% endblock %}


{% block content %}
<table class="table">
    
    <tr>
    {% for director in object_list %}

    <thead class="thead-dark">
        <tr>
            <th scope="col">Director</th>
            <th scope="col">Información Director</th>
        </tr>
    </thead>
        <td>
            <span class="nombre_director">{{ director }}</span>
        </td>
        <td>
            <blockquote class="blockquote text-left">
                <a href='/{{director.id}}' target="_parent"><buttontype="button" class="btn btn-info">Ver Director</button></a>
              </blockquote>
        </td>
        {% cycle '' '' '</tr><tr>' %}
    {% empty %}
        <td>No hay directores aún</td>
    {% endfor %}
    </tr>
</table>
{% endblock %}

Session_12/peliculas/templates/peliculas/pelicula.html
{% extends "peliculas/base.html" %}

{% block title %}Pelicula - {{ pelicula }}{% endblock %}

{% block header-title %}{{ pelicula }}{% endblock %}

{% block content %}

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Año publicacion</th>
      <th scope="col">Sinopsis</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{ pelicula.anyo}}</th>
      <th scope="row">{{ pelicula.sinopsis | linebreaks }}</th>
      
    </tr>
  </tbody>
</table>  

<blockquote class="blockquote text-center">
  <a href="http://localhost:8000/" target="_parent"><buttontype="button" class="btn btn-info">Regresar al Inicio</button></a>
</blockquote>


{% endblock %}